# Generated by Django 3.0.8 on 2020-07-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200723_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
