# Generated by Django 3.0.8 on 2020-07-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
